(define-resource changeRequest ()
  :class (s-prefix "ext:ChangeRequest")
  :properties `((:naam :string ,(s-prefix "skos:prefLabel"))
                (:event-type :string ,(s-prefix "ext:eventType")) ;; https://thesaurus.onroerenderfgoed.be/conceptschemes/GEBEURTENISTYPES/c?type=all&label=
                (:created-at :datetime ,(s-prefix "dct:created"))
                (:approved-at :datetime ,(s-prefix "ext:approvedAt")))
  :has-one `((agent :via ,(s-prefix "ext:requester")
                :as "requester")
             (locatie :via ,(s-prefix "ext:forLocation")
                :as "location"))
  :resource-base (s-url "http://data.lblod.info/id/change-requests/")
  :features '(include-uri)
  :on-path "change-requests")

(define-resource agent ()
  :class (s-prefix "dct:Agent")
  :has-one `((contact-info :via ,(s-prefix "ext:has_contact_point")
                            :as "contact-info")
             (locatie :via ,(s-prefix "ext:has_current_or_former_residence")
                            :as "residentie"))
  :resource-base (s-url "http://data.lblod.info/id/erfgoed/")
  :features '(include-uri)
  :on-path "agents")

(define-resource organization(agent)
  :class (s-prefix "org:Organization")
  :properties `((:voorkeursnaam :string ,(s-prefix "skos:prefLabel")))
  :resource-base (s-url "http://data.lblod.info/id/organizations/")
  :features '(include-uri)
  :on-path "organizations"
)

(define-resource persoon (agent)
:class (s-prefix "person:Person")
:properties `((:achternaam :string ,(s-prefix "foaf:familyName"))
              (:gebruikte-voornaam :string ,(s-prefix "persoon:gebruikteVoornaam")))
:resource-base (s-url "http://data.lblod.info/id/personen/")
:features '(include-uri)
:on-path "personen")


(define-resource contact-info ()
  :class (s-prefix "org:ContactPoint")
  :properties `((:email :string ,(s-prefix "org:email"))
                (:telefoon :string ,(s-prefix "org:telephone")))
  :has-one `((adres :via ,(s-prefix "locn:address")
                    :as "adres"))
  :features '(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/contact-info/")
  :on-path "contact-info")

(define-resource adres ()
:class (s-prefix "locn:Address")
:properties `((:busnummer :string ,(s-prefix "adres:Adresvoorstelling.busnummer"))
              (:huisnummer :string ,(s-prefix "adres:Adresvoorstelling.huisnummer"))
              (:straatnaam :string ,(s-prefix "locn:thoroughfare"))
              (:postcode :string ,(s-prefix "locn:postCode"))
              (:gemeentenaam :string ,(s-prefix "adres:gemeentenaam"))
              (:land :language-string-set ,(s-prefix "adres:land"))
              (:locatieaanduiding :string ,(s-prefix "locn:locatorDesignator"))
              (:locatienaam :language-string-set ,(s-prefix "locn:locatorName"))
              (:postbus :string ,(s-prefix "locn:poBox"))
              (:postnaam :string ,(s-prefix "locn:postName"))
              (:volledig-adres :string ,(s-prefix "locn:fullAddress")))
:features '(include-uri)
:resource-base (s-url "http://data.lblod.info/id/adressen/")
:on-path "adressen")

(define-resource bestuurseenheid (organization)
  :class (s-prefix "besluit:Bestuurseenheid")
  :properties `((:naam :string ,(s-prefix "skos:prefLabel")))
  :has-one `((locatie :via ,(s-prefix "besluit:werkingsgebied")
                             :as "locatie")
             (bestuurseenheid-classificatie-code :via ,(s-prefix "besluit:classificatie")
                                                 :as "classificatie"))
  :has-many `((agent :via ,(s-prefix "ext:agent")))
  :resource-base (s-url "http://data.lblod.info/id/bestuurseenheden/")
  :features '(include-uri)
  :on-path "bestuurseenheden")

(define-resource bestuurseenheid-classificatie-code ()
  :class (s-prefix "ext:BestuurseenheidClassificatieCode")
  :properties `((:label :string ,(s-prefix "skos:prefLabel")))
  :resource-base (s-url "http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/")
  :features '(include-uri)
  :on-path "bestuurseenheid-classificatie-codes")

(define-resource locatie () 
  :class (s-prefix "prov:Location")
  :properties `((:naam :string ,(s-prefix "rdfs:label")))
  :has-many `((bestuurseenheid :via ,(s-prefix "besluit:werkingsgebied")
                               :inverse t
                               :as "bestuurseenheid"))
  :resource-base (s-url "http://data.lblod.info/id/locaties/")
  :features '(include-uri)
  :on-path "locaties")
