(in-package :mu-cl-resources)

(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "rdfs" "http://www.w3.org/2000/01/rdf-schema#")
(add-prefix "nfo" "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")
(add-prefix "nie" "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#")
(add-prefix "dbpedia" "http://dbpedia.org/ontology/")
(add-prefix "prov" "http://www.w3.org/ns/prov#")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "adms" "http://www.w3.org/ns/adms#")
(add-prefix "task" "http://redpencil.data.gift/vocabularies/tasks/")
(add-prefix "schema" "https://schema.org/")
(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "persoon" "https://data.vlaanderen.be/ns/persoon#")
(add-prefix "person" "http://www.w3.org/ns/person#")
(add-prefix "locn" "http://www.w3.org/ns/locn#")
(add-prefix "adres" "https://data.vlaanderen.be/ns/adres#")
(add-prefix "besluit" "http://data.vlaanderen.be/ns/besluit#")
(add-prefix "org" "http://www.w3.org/ns/org#")

